//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatam_Car.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string State { get; set; }
        public string CallNumber { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<double> Price { get; set; }
        public string Report { get; set; }
    }
}
